"""
Python Client Generator — generates an async Python client from an Anchor IDL.

Output files:
  client/client.py        — Async client class with typed methods
  client/types.py         — Python dataclasses for all account types
  client/requirements.txt
"""

import textwrap
from pathlib import Path
from src.models import AnchorIDL, IdlInstruction, IdlAccountType
from src.logger import get_logger

logger = get_logger(__name__)


class PythonGenerator:
    def generate(self, idl: AnchorIDL, output_dir: str) -> dict[str, str]:
        """
        Generate Python client files for the given IDL.

        Parameters:
        - idl: Parsed AnchorIDL
        - output_dir: Root output directory

        Returns:
        - dict: {filename: content} for all generated files
        """
        client_dir = Path(output_dir) / "client"
        client_dir.mkdir(parents=True, exist_ok=True)

        files = {
            "client/client.py":         self._generate_client(idl),
            "client/types.py":          self._generate_types(idl),
            "client/requirements.txt":  self._generate_requirements(),
            "client/__init__.py":       self._generate_init(idl),
        }

        for rel_path, content in files.items():
            full_path = Path(output_dir) / rel_path
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(content, encoding="utf-8")
            logger.debug(f"Written: {full_path}")

        logger.info(f"Python client: {len(files)} files → {client_dir}")
        return files

    def _generate_client(self, idl: AnchorIDL) -> str:
        class_name = idl.class_name
        program_name = idl.name
        methods = "\n\n".join(self._generate_method(ix) for ix in idl.instructions)
        fetch_methods = "\n\n".join(
            self._generate_fetch_method(acc) for acc in idl.accounts
        )
        all_types = [acc.pascal_name for acc in idl.accounts]
        type_import = f"from .types import {', '.join(all_types)}" if all_types else ""

        return f'''"""
{class_name} — Python Async Client
Generated by IdlExplorer — LixerDev

Program: {program_name}  |  Version: {idl.version}
Address: {idl.address or "11111111111111111111111111111111"}

Usage:
    from client import {class_name}

    client = {class_name}(provider, program_id)
    tx_sig = await client.{idl.instructions[0].camel_name}(...)
"""

from __future__ import annotations
from typing import Optional
from solders.pubkey import Pubkey
from anchorpy import Program, Provider, Context, Idl
{type_import}


PROGRAM_ID = Pubkey.from_string("{idl.address or "11111111111111111111111111111111"}")


class {class_name}:
    """
    Async Python client for the {idl.display_name} Anchor program.

    All instruction methods are async and return transaction signatures (str).
    Account fetchers return typed dataclass instances or None if not found.
    """

    def __init__(self, provider: Provider, program_id: Pubkey = PROGRAM_ID):
        self.provider = provider
        self.program_id = program_id
        self.program: Optional[Program] = None

    async def __aenter__(self) -> "{class_name}":
        await self._load_program()
        return self

    async def __aexit__(self, *_):
        pass

    async def _load_program(self):
        """Load program from on-chain IDL. Call before using instruction methods."""
        self.program = await Program.at(self.program_id, self.provider)

    # ─── Instructions ─────────────────────────────────────────────────────────

{textwrap.indent(methods, "    ")}

    # ─── Account Fetchers ─────────────────────────────────────────────────────

{textwrap.indent(fetch_methods, "    ")}


async def create_{program_name}_client(
    provider: Provider,
    program_id: Pubkey = PROGRAM_ID,
) -> {class_name}:
    """Factory function — creates and initializes the client."""
    client = {class_name}(provider, program_id)
    await client._load_program()
    return client
'''

    def _generate_method(self, ix: IdlInstruction) -> str:
        """Generate an async method for one instruction."""
        # Args
        arg_params = ""
        if ix.args:
            arg_params = "".join(f",\n        {a.name}: {a.py_type}" for a in ix.args)

        has_accounts = bool(ix.accounts)
        accounts_param = ",\n        accounts: dict" if has_accounts else ""

        # Positional args for anchorpy call
        arg_names = ", ".join(a.name for a in ix.args)

        # Doc
        doc = ix.docs[0] if ix.docs else f"Execute the `{ix.name}` instruction."
        account_doc = ""
        if has_accounts:
            account_doc = "\n".join(
                f"        {acc.name}: PublicKey {'(mut)' if acc.is_mut else ''}"
                f"{'(signer)' if acc.is_signer else ''}"
                for acc in ix.accounts
            )

        return f'''async def {ix.name}(
        self{arg_params}{accounts_param},
    ) -> str:
        """
        {doc}

        Args:
{chr(10).join(f"            {a.name} ({a.py_type}): IDL type {a.type_str}" for a in ix.args) or "            (no args)"}

        Accounts:
{account_doc or "            (no accounts)"}

        Returns:
            str: Transaction signature
        """
        assert self.program, "Call _load_program() first or use async context manager"
        return await self.program.rpc["{ix.name}"](
            {arg_names},
            ctx=Context(
                accounts={"{" + "".join(f'"{acc.name}": accounts["{acc.name}"], ' for acc in ix.accounts) + "}"}
            ) if {str(has_accounts)} else Context(),
        )'''

    def _generate_fetch_method(self, acc: IdlAccountType) -> str:
        """Generate an async account fetcher method."""
        return f'''async def fetch_{acc.name.lower()}(
        self,
        address: Pubkey,
    ) -> Optional[{acc.pascal_name}]:
        """Fetch and decode a {acc.pascal_name} account from the chain."""
        assert self.program, "Call _load_program() first"
        try:
            raw = await self.program.account["{acc.name}"].fetch(address)
            return {acc.pascal_name}(**{{k: v for k, v in raw.__dict__.items() if not k.startswith("_")}})
        except Exception:
            return None

    async def fetch_all_{acc.name.lower()}(self) -> list[{acc.pascal_name}]:
        """Fetch all {acc.pascal_name} accounts for this program."""
        assert self.program, "Call _load_program() first"
        accounts = await self.program.account["{acc.name}"].all()
        return [
            {acc.pascal_name}(**{{k: v for k, v in a.account.__dict__.items() if not k.startswith("_")}})
            for a in accounts
        ]'''

    def _generate_types(self, idl: AnchorIDL) -> str:
        """Generate types.py with Python dataclasses."""
        sections = [f'''"""
types.py — Python dataclasses for {idl.display_name}
Generated by IdlExplorer — LixerDev
"""

from __future__ import annotations
from dataclasses import dataclass
from typing import Optional, List
from solders.pubkey import Pubkey
''']

        for acc in idl.accounts:
            fields = "\n".join(
                f"    {f.name}: {f.py_type}"
                for f in acc.fields
            ) or "    pass"
            sections.append(f"@dataclass\nclass {acc.pascal_name}:\n    \"\"\"{acc.name} account.\"\"\"\n{fields}")

        for t in idl.types:
            if t.kind == "struct":
                fields = "\n".join(f"    {f.name}: {f.py_type}" for f in t.fields) or "    pass"
                sections.append(f"@dataclass\nclass {t.name}:\n{fields}")
            elif t.kind == "enum":
                # Python enum
                variants = "\n".join(f"    {v.name} = \"{v.name}\"" for v in t.variants)
                sections.append(f"from enum import Enum\n\nclass {t.name}(Enum):\n{variants}")

        return "\n\n\n".join(sections) + "\n"

    def _generate_requirements(self) -> str:
        return """anchorpy>=0.20.0
solders>=0.21.0
solana>=0.34.0
"""

    def _generate_init(self, idl: AnchorIDL) -> str:
        return f'''"""
{idl.display_name} Python Client
Generated by IdlExplorer — LixerDev
"""

from .client import {idl.class_name}, create_{idl.name}_client
from .types import *

__all__ = ["{idl.class_name}", "create_{idl.name}_client"]
'''
