"""
TypeScript SDK Generator — generates a typed SDK from an Anchor IDL.

Output files:
  sdk/index.ts    — Main client class with methods per instruction
  sdk/types.ts    — TypeScript interfaces for all account types
  sdk/errors.ts   — Typed error classes
  sdk/package.json
"""

import json
import textwrap
from pathlib import Path
from src.models import AnchorIDL, IdlInstruction, IdlAccountType, IdlCustomType, IdlError
from src.logger import get_logger

logger = get_logger(__name__)


class TypeScriptGenerator:
    def generate(self, idl: AnchorIDL, output_dir: str) -> dict[str, str]:
        """
        Generate TypeScript SDK files for the given IDL.

        Parameters:
        - idl: Parsed AnchorIDL
        - output_dir: Root output directory

        Returns:
        - dict: {filename: content} for all generated files
        """
        sdk_dir = Path(output_dir) / "sdk"
        sdk_dir.mkdir(parents=True, exist_ok=True)

        files = {
            "sdk/index.ts":    self._generate_index(idl),
            "sdk/types.ts":    self._generate_types(idl),
            "sdk/errors.ts":   self._generate_errors(idl),
            "sdk/package.json": self._generate_package_json(idl),
        }

        for rel_path, content in files.items():
            full_path = Path(output_dir) / rel_path
            full_path.parent.mkdir(parents=True, exist_ok=True)
            full_path.write_text(content, encoding="utf-8")
            logger.debug(f"Written: {full_path}")

        logger.info(f"TypeScript SDK: {len(files)} files → {sdk_dir}")
        return files

    def _generate_index(self, idl: AnchorIDL) -> str:
        class_name = idl.class_name
        program_name = idl.name
        methods = "\n\n".join(self._generate_method(ix, idl) for ix in idl.instructions)
        fetch_account_methods = "\n\n".join(
            self._generate_fetch_method(acc) for acc in idl.accounts
        )
        all_types = [acc.name for acc in idl.accounts] + [t.name for t in idl.types]
        type_imports = ", ".join(all_types) if all_types else ""

        return f'''/**
 * {class_name} — TypeScript SDK
 * Generated by IdlExplorer — LixerDev
 *
 * Program: {program_name}  |  Version: {idl.version}
 * Address: {idl.address or "11111111111111111111111111111111"}
 */

import {{
  Program,
  AnchorProvider,
  BN,
  web3,
}} from "@coral-xyz/anchor";
import {{ PublicKey, TransactionSignature }} from "@solana/web3.js";
{f'import {{ {type_imports} }} from "./types";' if type_imports else ""}
import * as IDL_JSON from "./idl.json";

// ─── Types ────────────────────────────────────────────────────────────────────

export type Cluster = "mainnet-beta" | "devnet" | "testnet" | "localnet";

export interface {class_name}Config {{
  programId?: PublicKey;
  cluster?: Cluster;
}}

// ─── Client Class ─────────────────────────────────────────────────────────────

export class {class_name} {{
  readonly program: Program;
  readonly provider: AnchorProvider;
  readonly programId: PublicKey;

  constructor(provider: AnchorProvider, programId?: PublicKey) {{
    this.provider = provider;
    this.programId = programId ?? new PublicKey("{idl.address or "11111111111111111111111111111111"}");
    this.program = new Program(IDL_JSON as any, this.provider);
  }}

  // ─── Instructions ────────────────────────────────────────────────────────

{textwrap.indent(methods, "  ")}

  // ─── Account Fetchers ────────────────────────────────────────────────────

{textwrap.indent(fetch_account_methods, "  ")}
}}

// ─── Factory ──────────────────────────────────────────────────────────────────

export function create{class_name}(
  provider: AnchorProvider,
  programId?: PublicKey,
): {class_name} {{
  return new {class_name}(provider, programId);
}}
'''

    def _generate_method(self, ix: IdlInstruction, idl: AnchorIDL) -> str:
        """Generate a typed async method for one instruction."""
        has_args = bool(ix.args)
        has_accounts = bool(ix.accounts)

        # Arg params
        arg_params = ", ".join(f"{a.name}: {a.ts_type}" for a in ix.args)

        # Accounts type
        accounts_interface = ""
        if has_accounts:
            acc_fields = "\n".join(
                f"    {acc.name}{' ?' if acc.is_optional else ''}: PublicKey;"
                for acc in ix.accounts
            )
            accounts_interface = f"  /** Account inputs for {ix.camel_name} */\n  export interface {ix.pascal_name}Accounts {{\n{acc_fields}\n  }}"

        # Method signature
        params = []
        if has_args:
            params.append(f"args: {{ {arg_params} }}")
        if has_accounts:
            params.append(f"accounts: {ix.pascal_name}Accounts")

        params_str = ", ".join(params)

        # Method call chain
        arg_names = [f"args.{a.name}" for a in ix.args]
        arg_call = ", ".join(arg_names)

        # Docs
        doc_lines = "\n   * ".join(ix.docs) if ix.docs else f"Execute the `{ix.name}` instruction."

        method = f'''/**
   * {doc_lines}
   */
  async {ix.camel_name}(
    {params_str}
  ): Promise<TransactionSignature> {{
    return await this.program.methods
      .{ix.camel_name}({arg_call})
      {".accounts(accounts)" if has_accounts else ""}
      .rpc();
  }}'''

        if accounts_interface:
            method = accounts_interface + "\n\n  " + method

        return method

    def _generate_fetch_method(self, acc: IdlAccountType) -> str:
        """Generate a typed account fetcher method."""
        camel_name = acc.name[0].lower() + acc.name[1:]
        return f'''/**
   * Fetch a {acc.pascal_name} account from the chain.
   */
  async fetch{acc.pascal_name}(address: PublicKey): Promise<{acc.pascal_name} | null> {{
    try {{
      return await this.program.account.{camel_name}.fetch(address);
    }} catch {{
      return null;
    }}
  }}

  /**
   * Subscribe to {acc.pascal_name} account changes.
   */
  on{acc.pascal_name}Change(
    address: PublicKey,
    callback: (account: {acc.pascal_name}) => void,
  ): number {{
    return this.program.account.{camel_name}.subscribe(address)
      .on("change", callback) as unknown as number;
  }}'''

    def _generate_types(self, idl: AnchorIDL) -> str:
        """Generate types.ts with all account and custom type interfaces."""
        sections = [f'''/**
 * types.ts — TypeScript type definitions
 * Generated by IdlExplorer — LixerDev
 * Program: {idl.name}
 */

import {{ BN }} from "@coral-xyz/anchor";
import {{ PublicKey }} from "@solana/web3.js";
''']

        # Account types
        for acc in idl.accounts:
            fields = "\n".join(
                f"  {f.name}: {f.ts_type};"
                for f in acc.fields
            )
            sections.append(f"export interface {acc.pascal_name} {{\n{fields}\n}}")

        # Custom types
        for t in idl.types:
            if t.kind == "struct":
                fields = "\n".join(f"  {f.name}: {f.ts_type};" for f in t.fields)
                sections.append(f"export interface {t.name} {{\n{fields}\n}}")
            elif t.kind == "enum":
                variants = " | ".join(
                    f'{{ kind: "{v.name}" }}'
                    for v in t.variants
                )
                sections.append(f"export type {t.name} = {variants};")

        return "\n\n".join(sections) + "\n"

    def _generate_errors(self, idl: AnchorIDL) -> str:
        """Generate errors.ts with typed error classes."""
        class_defs = ""
        if idl.errors:
            class_defs = "\n".join(
                f'''export class {err.class_name} extends Error {{
  readonly code = {err.code};
  constructor() {{ super("{err.msg or err.name}"); this.name = "{err.class_name}"; }}
}}'''
                for err in idl.errors
            )

        error_map_entries = "\n".join(
            f"  {err.code}: {err.class_name},"
            for err in idl.errors
        )

        return f'''/**
 * errors.ts — Typed error classes
 * Generated by IdlExplorer — LixerDev
 * Program: {idl.name}
 */

{class_defs}

/** Map of error codes to error classes */
export const ERRORS: Record<number, new () => Error> = {{
{error_map_entries}
}};

/** Parse a raw anchor error and return a typed Error instance. */
export function parseError(code: number): Error {{
  const Cls = ERRORS[code];
  return Cls ? new Cls() : new Error(`Unknown error code: ${{code}}`);
}}
'''

    def _generate_package_json(self, idl: AnchorIDL) -> str:
        return json.dumps({
            "name": f"@lixerdev/{idl.name.replace('_', '-')}-sdk",
            "version": idl.version,
            "description": f"TypeScript SDK for {idl.display_name} — generated by IdlExplorer",
            "main": "dist/index.js",
            "types": "dist/index.d.ts",
            "scripts": {
                "build": "tsc",
                "lint": "eslint src --ext .ts"
            },
            "dependencies": {
                "@coral-xyz/anchor": "^0.30.0",
                "@solana/web3.js": "^1.95.0",
                "bn.js": "^5.2.1"
            },
            "devDependencies": {
                "typescript": "^5.0.0",
                "@types/bn.js": "^5.1.5"
            }
        }, indent=2)
